CREATE TABLE tb_users (
    id UUID PRIMARY KEY,
    name CHARACTER VARYING(150) NOT NULL,
    email CHARACTER VARYING(150) NOT NULL UNIQUE,
    password CHARACTER VARYING(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);
