name: CI Back-End

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "dev" ]

jobs:
  build:
    name: Build + Test + Sonar
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: eyes_project_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d eyes_project_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Dar permissão ao Maven
        run: chmod +x ./mvnw

      - name: Validar toolchain
        shell: pwsh
        run: ./scripts/check-toolchain.ps1

      - name: Build + Testes
        run: ./mvnw clean verify -Dspring.profiles.active=test
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: eyes_project_db
          DB_USER: postgres
          DB_PASSWORD: postgres
          JWT_SECRET: testing_secret_key

      - name: Rodar SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw org.sonarsource.scanner.maven:sonar-maven-plugin:5.7.0.6970:sonar \
          -Dsonar.projectKey=Renato-Cesarr_Eyes-Project-Back \
          -Dsonar.organization=renato-cesarr \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.exclusions=**/*.sql \
          -Dsonar.coverage.exclusions=src/main/java/br/com/eyesproject/eyes_project_back/global/**/*,src/main/java/br/com/eyesproject/eyes_project_back/**/domain/models/*,src/main/java/br/com/eyesproject/eyes_project_back/**/presentation/dto/*
